# Generated by Django 3.0.8 on 2021-06-09 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20210608_2142'),
        ('Relaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigos',
            name='Amigo1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios'),
        ),
    ]
