# Generated by Django 3.0.8 on 2021-05-28 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coment', models.CharField(max_length=50)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='Comentarios')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.CharField(max_length=1000)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='Mensajes')),
                ('TO_usuario', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('FROM_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50, null=True)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='Posts')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PostsDesactivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Posts')),
            ],
            options={
                'verbose_name': 'PostDesactivo',
                'verbose_name_plural': 'PostsDesactivos',
            },
        ),
        migrations.CreateModel(
            name='PostsActivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Posts')),
            ],
            options={
                'verbose_name': 'PostActivo',
                'verbose_name_plural': 'PostsActivos',
            },
        ),
        migrations.CreateModel(
            name='MensajesDesactivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Mensajes')),
            ],
            options={
                'verbose_name': 'MensajeDesctivo',
                'verbose_name_plural': 'MensajesDesactivos',
            },
        ),
        migrations.CreateModel(
            name='MensajesActivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Mensajes')),
            ],
            options={
                'verbose_name': 'MensajeActivo',
                'verbose_name_plural': 'MensajesActivos',
            },
        ),
        migrations.CreateModel(
            name='ComentariosDesactivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Comentarios')),
            ],
            options={
                'verbose_name': 'ComentarioDesactivo',
                'verbose_name_plural': 'ComentariosDesactivos',
            },
        ),
        migrations.CreateModel(
            name='ComentariosActivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Comentarios')),
            ],
            options={
                'verbose_name': 'ComentarioActivo',
                'verbose_name_plural': 'ComentariosActivos',
            },
        ),
        migrations.AddField(
            model_name='comentarios',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Posts'),
        ),
    ]
