# Generated by Django 3.0.8 on 2021-10-02 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Relaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coment', models.CharField(max_length=50)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='Comentarios')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.CharField(max_length=1000)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='Mensajes')),
                ('TO_usuario', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recibido', models.BooleanField(default=False)),
                ('FROM_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50, null=True)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='Posts')),
                ('me_gustas', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PostsDesactivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Posts')),
            ],
            options={
                'verbose_name': 'PostDesactivo',
                'verbose_name_plural': 'PostsDesactivos',
            },
        ),
        migrations.CreateModel(
            name='PostsActivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Posts')),
            ],
            options={
                'verbose_name': 'PostActivo',
                'verbose_name_plural': 'PostsActivos',
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificacion', models.CharField(max_length=20)),
                ('img_de', models.ImageField(blank=True, null=True, upload_to='Notificaciones')),
                ('para', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('recibido', models.BooleanField(default=False)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Social.Posts')),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Relaciones.Solicitudes')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificiones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MensajesDesactivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Mensajes')),
            ],
            options={
                'verbose_name': 'MensajeDesctivo',
                'verbose_name_plural': 'MensajesDesactivos',
            },
        ),
        migrations.CreateModel(
            name='MensajesActivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Mensajes')),
            ],
            options={
                'verbose_name': 'MensajeActivo',
                'verbose_name_plural': 'MensajesActivos',
            },
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='ComentariosDesactivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Comentarios')),
            ],
            options={
                'verbose_name': 'ComentarioDesactivo',
                'verbose_name_plural': 'ComentariosDesactivos',
            },
        ),
        migrations.CreateModel(
            name='ComentariosActivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Comentarios')),
            ],
            options={
                'verbose_name': 'ComentarioActivo',
                'verbose_name_plural': 'ComentariosActivos',
            },
        ),
        migrations.AddField(
            model_name='comentarios',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social.Posts'),
        ),
    ]
