# Generated by Django 3.0.8 on 2021-10-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='notificacion',
            field=models.CharField(max_length=100),
        ),
    ]
