# Generated by Django 3.0.8 on 2021-10-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0002_auto_20211002_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Descripcion',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
