# Generated by Django 3.0.8 on 2021-06-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0002_notificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
