# Generated by Django 3.0.8 on 2021-06-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0004_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='me_gustas',
            field=models.IntegerField(default=0),
        ),
    ]
