# Generated by Django 3.0.8 on 2021-06-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0005_posts_me_gustas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificaciones',
            options={'ordering': ['-fecha'], 'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificiones'},
        ),
        migrations.AddField(
            model_name='mensajes',
            name='recibido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='recibido',
            field=models.BooleanField(default=False),
        ),
    ]
