# Generated by Django 3.0.8 on 2021-06-05 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0006_auto_20210605_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Social.Posts'),
        ),
    ]
