# Generated by Django 3.0.8 on 2021-06-05 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relaciones', '0001_initial'),
        ('Social', '0007_auto_20210605_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Relaciones.Solicitudes'),
        ),
    ]
