# Generated by Django 3.0.8 on 2021-06-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20210608_2142'),
        ('Social', '0008_notificaciones_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios'),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='FROM_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios'),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='de',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios'),
        ),
    ]
